mobile-friendly and datatables for views
thedevdojo/chatter pull request #184
Opened 2018-02-14 08:00 UTC by galdazbiz

It's a first approximation, it can be improved but it's a good start for a mobile-friendly forum :)
I added it into a new folder so the people can choose, but I think the idea would be to merge at some point.

2018-02-15 14:24 UTC, marktopper commented
Thanks, but those are not actually used in the system.
We would be open for a solution where the user can choose to use your set of views or have them working with the current set of views.

Thanks.

2018-02-21 16:11 UTC, galdazbiz commented
Any dev or contributor can help with linking the views to the routes/controller? I'm better at frontend than programming.

2018-04-02 09:43 UTC, marktopper requested changes

2018-04-02 09:43 UTC, marktopper commented on composer.json
> +    "name": "tronne/chatter",
Don't change the package name.

2018-04-02 10:46 UTC, galdazbiz commented
I cancel this to continue with my develop rather than improving the original code because it take too much time

2018-04-02 10:46 UTC, closed without merging